#!/bin/bash
if [ ! -f .tool-versions ]; then
  echo ".tool-versions file not found!"
  exit 1
fi

ASDF = $(which asdf)
if [ -z "$ASDF" ]; then
  echo "asdf not found!"
  exit 1
fi
echo "using asdf located in $ASDF"

cat .tool-versions | awk '{print $1}' | while read -r plugin; do
  if [ -z "$plugin" ]; then
    continue
  fi

  ret=$(asdf plugin-list | grep $plugin)
  if [ $? -eq 0 ]; then
    echo "$plugin is already installed. Skipping"
  else
    echo "Installing $plugin"
    $ASDF plugin-add $plugin
    ex=$?
    if [ $ex -eq 2 ] || [ $ex -eq 0 ]; then
      echo "Successfully installed $plugin"
    else
      echo "Error installing $plugin"
      exit $ex
    fi

    if [ $plugin = "nodejs" ]; then
      bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
    fi
  fi
done
