#!/bin/bash
if [ ! -f .tool-versions ]; then
  echo ".tool-versions file not found!"
  exit 1
fi

ASDF = $(which asdf || echo "/root/.asdf/bin/asdf")
if [ -z "$ASDF" ]; then
  echo "asdf not found!"
  exit 1
fi
echo "using asdf located in $ASDF"

cat .tool-versions | while read -r version; do
  if [ -z "$version" ]; then
    continue
  fi

  ret=$(asdf where $version)
  ex=$?
  if [ $ex -eq 0 ]; then
    echo "$version is already installed. Reshimming"
    $ASDF reshim $version
  else
    echo "$version is not installed. Trying to install..."
    $ASDF install $version
    ex=$?
    if [ $ex -ne 0 ]; then
      echo "Error installing $version"
      exit $ex
    fi
  fi
done
