version: 2.1
jobs:
  build-base:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: v1-docker-base-cache-{{ checksum "Dockerfile" }}
      - run:
          command: |
            set +o pipefail
            docker load -i /caches/asdf.tar | true
      - run:
          command: |
            docker build --cache-from=asdf -t asdf .
      - run:
          command: |
            mkdir -p /caches
            docker save -o /caches/asdf.tar asdf

      - save_cache:
          key: v1-docker-base-cache-{{ checksum "Dockerfile" }}
          path: /caches/asdf-base.tar
  asdf-install:
    docker:
      - image: asdf
        environment:
          BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      - restore_cache:
          key: v1-tools-cache-{{ checksum ".tool-versions" }}

      - run: asdf-install-plugins
      - run: asdf-install-versions

      - save_cache:
          key: v1-tools-cache-{{ checksum ".tool-versions" }}
          paths:
            - "~/.asdf/plugins"
            - "~/.asdf/installs"

      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  build:
    jobs:
      - build-base
      - asdf-install
