version: 2.1
jobs:
  build_base:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: v1-docker-base-cache-{{ checksum "Dockerfile" }}
      - run:
          command: |
            set +o pipefail
            docker load -i /caches/asdf.tar | true
      - run:
          command: |
            docker build --cache-from=asdf -t asdf .
      - run:
          command: |
            mkdir -p /caches
            docker save -o /caches/asdf.tar asdf
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag asdf jeremylempereur/asdf:latest
            docker push jeremylempereur/asdf:latest

      - save_cache:
          key: v1-docker-base-cache-{{ checksum "Dockerfile" }}
          paths:
            - /caches/asdf-base.tar
  asdf_install:
    docker:
      - image: jeremylempereur/asdf
    steps:
      - checkout
      - restore_cache:
          key: v1-tools-cache-{{ checksum ".tool-versions" }}

      - run: asdf-install-plugins
      - run: asdf-install-versions

      - save_cache:
          key: v1-tools-cache-{{ checksum ".tool-versions" }}
          paths:
            - "~/.asdf/plugins"
            - "~/.asdf/installs"
workflows:
  version: 2
  build:
    jobs:
      - build_base
      - asdf_install
          requires:
            - build_base
