version: 2.1
jobs:
  build:
    docker:
      - image: lisinge/asdf:latest
        environment:
          BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-tools-cache-{{ checksum ".tool-versions" }}

      - run: asdf-install-plugins
      - run: asdf-install-versions

      - save_cache:
          key: v1-tools-cache-{{ checksum ".tool-versions" }}
          paths:
            - "~/.asdf/plugins"
            - "~/.asdf/installs"

      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
